"""Add platform fields to Merchant

Revision ID: b85c21bf1ba9
Revises: cb9b9614736a
Create Date: 2026-01-31 21:10:12.938402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85c21bf1ba9'
down_revision: Union[str, Sequence[str], None] = 'cb9b9614736a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False, server_default='shopify'))
        batch_op.add_column(sa.Column('platform_context', sa.JSON(), nullable=True))
        batch_op.alter_column('enable_multi_plan_strategy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.alter_column('enable_multi_plan_strategy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('platform_context')
        batch_op.drop_column('platform')


    # ### end Alembic commands ###
