"""initial_full_schema

Revision ID: cb9b9614736a
Revises: 
Create Date: 2026-01-22 10:58:41.359426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9b9614736a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_strategy_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_key', sa.String(length=255), nullable=False),
    sa.Column('industry_type', sa.String(length=50), nullable=True),
    sa.Column('strategy_key', sa.String(length=50), nullable=False),
    sa.Column('p50_conversion', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('p90_conversion', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('avg_roi_p50', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recommendation_score', sa.Float(), nullable=False),
    sa.Column('context_criteria', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_strategy_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_strategy_patterns_pattern_key'), ['pattern_key'], unique=False)

    op.create_table('global_strategy_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry_type', sa.String(length=50), nullable=False),
    sa.Column('skill_name', sa.String(length=50), nullable=False),
    sa.Column('recommended_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_lift', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governor_risk_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('min_trust_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governor_risk_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governor_risk_policies_agent_type'), ['agent_type'], unique=False)

    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shopify_domain', sa.String(length=255), nullable=False),
    sa.Column('shopify_shop_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_auto_discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_auto_ad_spend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('monthly_llm_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_llm_spend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('budget_reset_date', sa.DateTime(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('governor_aggressive_mode', sa.Boolean(), nullable=False),
    sa.Column('governor_calibration_threshold', sa.Integer(), nullable=False),
    sa.Column('governor_trust_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dna_status', sa.String(length=20), nullable=False),
    sa.Column('klaviyo_api_key', sa.Text(), nullable=True),
    sa.Column('twilio_account_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_auth_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopify_domain'),
    sa.UniqueConstraint('shopify_shop_id')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index('idx_merchant_domain', ['shopify_domain'], unique=False)

    op.create_table('agent_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('allowed_scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('agent_clients', schema=None) as batch_op:
        batch_op.create_index('idx_agent_client_client_id', ['client_id'], unique=False)
        batch_op.create_index('idx_agent_client_merchant', ['merchant_id'], unique=False)

    op.create_table('agent_thoughts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('thought_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detailed_reasoning', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_thoughts', schema=None) as batch_op:
        batch_op.create_index('idx_thought_created', ['created_at'], unique=False)
        batch_op.create_index('idx_thought_merchant_agent', ['merchant_id', 'agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_thoughts_execution_id'), ['execution_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_agent_type', sa.String(length=50), nullable=True),
    sa.Column('delegated_by', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('authorization_id', sa.String(length=100), nullable=True),
    sa.Column('scopes_used', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_execution_id'), ['execution_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_segments', sa.JSON(), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('content_snapshot', sa.JSON(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('emails_opened', sa.Integer(), nullable=False),
    sa.Column('emails_clicked', sa.Integer(), nullable=False),
    sa.Column('sms_sent', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('origin_execution_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_merchant_status', ['merchant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_origin_execution_id'), ['origin_execution_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shopify_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('recency_score', sa.Integer(), nullable=True),
    sa.Column('frequency_score', sa.Integer(), nullable=True),
    sa.Column('monetary_score', sa.Integer(), nullable=True),
    sa.Column('rfm_segment', sa.String(length=50), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_order_date', sa.DateTime(), nullable=True),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('email_optin', sa.Boolean(), nullable=False),
    sa.Column('sms_optin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_customer_last_order', ['last_order_date'], unique=False)
        batch_op.create_index('idx_customer_merchant_segment', ['merchant_id', 'rfm_segment'], unique=False)

    op.create_table('inbox_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposal_data', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('origin_execution_id', sa.String(length=36), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.create_index('idx_inbox_created', ['created_at'], unique=False)
        batch_op.create_index('idx_inbox_merchant_status', ['merchant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbox_items_origin_execution_id'), ['origin_execution_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agent_stake', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('attribution_source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('llm_usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_journeys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('journey_type', sa.String(length=50), nullable=False),
    sa.Column('target_metric', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_scope_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant_scope_grants', schema=None) as batch_op:
        batch_op.create_index('idx_scope_grant_merchant_agent', ['merchant_id', 'agent_type'], unique=False)
        batch_op.create_index('idx_scope_grant_scope', ['scope'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shopify_product_id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('variant_count', sa.Integer(), nullable=False),
    sa.Column('units_sold_30d', sa.Integer(), nullable=False),
    sa.Column('units_refunded_30d', sa.Integer(), nullable=False),
    sa.Column('units_sold_60d', sa.Integer(), nullable=False),
    sa.Column('units_sold_90d', sa.Integer(), nullable=False),
    sa.Column('revenue_30d', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_sale_date', sa.DateTime(), nullable=True),
    sa.Column('velocity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_dead_stock', sa.Boolean(), nullable=False),
    sa.Column('dead_stock_severity', sa.String(length=20), nullable=True),
    sa.Column('days_since_last_sale', sa.Integer(), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('holding_cost_per_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_product_last_sale', ['last_sale_date'], unique=False)
        batch_op.create_index('idx_product_merchant_dead', ['merchant_id', 'is_dead_stock'], unique=False)
        batch_op.create_index('idx_product_velocity', ['velocity_score'], unique=False)

    op.create_table('store_dna',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('aov_p50', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('aov_p90', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_revenue_30d', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('brand_tone', sa.String(length=50), nullable=False),
    sa.Column('industry_type', sa.String(length=50), nullable=False),
    sa.Column('brand_values', sa.JSON(), nullable=False),
    sa.Column('brand_guide_raw', sa.Text(), nullable=True),
    sa.Column('brand_guide_parsed', sa.JSON(), nullable=True),
    sa.Column('scraped_homepage_meta', sa.JSON(), nullable=True),
    sa.Column('scraped_about_content', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('identity_description', sa.Text(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('raw_discovery_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_vault',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('connection_name', sa.String(length=100), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('scopes_granted', sa.JSON(), nullable=True),
    sa.Column('scopes_requested', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('retry_attempts', sa.Integer(), nullable=False),
    sa.Column('max_retry_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('permanent_failure_at', sa.DateTime(), nullable=True),
    sa.Column('merchant_notified_of_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_vault', schema=None) as batch_op:
        batch_op.create_index('idx_token_vault_merchant_provider', ['merchant_id', 'provider'], unique=False)
        batch_op.create_index('idx_token_vault_status', ['status'], unique=False)

    op.create_table('action_reversals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('audit_log_id', sa.String(length=36), nullable=False),
    sa.Column('reversal_type', sa.String(length=50), nullable=False),
    sa.Column('original_state', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reversal_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_reversals', schema=None) as batch_op:
        batch_op.create_index('idx_reversal_merchant', ['merchant_id'], unique=False)

    op.create_table('async_auth_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('auth_req_id', sa.String(length=100), nullable=False),
    sa.Column('inbox_item_id', sa.String(length=36), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('authorization_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_channel', sa.String(length=50), nullable=True),
    sa.Column('push_sent_at', sa.DateTime(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inbox_item_id'], ['inbox_items.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_req_id')
    )
    with op.batch_alter_table('async_auth_requests', schema=None) as batch_op:
        batch_op.create_index('idx_async_auth_inbox', ['inbox_item_id'], unique=False)
        batch_op.create_index('idx_async_auth_merchant', ['merchant_id'], unique=False)
        batch_op.create_index('idx_async_auth_status', ['status'], unique=False)

    op.create_table('commercial_journeys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('journey_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_touch', sa.Integer(), nullable=False),
    sa.Column('next_touch_due_at', sa.DateTime(), nullable=False),
    sa.Column('last_touch_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floor_pricing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('shopify_product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('floor_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('liquidation_mode', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('floor_pricing', schema=None) as batch_op:
        batch_op.create_index('idx_floor_pricing_merchant', ['merchant_id'], unique=False)
        batch_op.create_index('idx_floor_pricing_sku', ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_floor_pricing_shopify_product_id'), ['shopify_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_floor_pricing_sku'), ['sku'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shopify_order_id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopify_order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_order_customer', ['customer_id'], unique=False)
        batch_op.create_index('idx_order_merchant_date', ['merchant_id', 'created_at'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shopify_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopify_variant_id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index('idx_variant_product', ['product_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('idx_orderitem_order', ['order_id'], unique=False)
        batch_op.create_index('idx_orderitem_product', ['product_id'], unique=False)

    op.create_table('touch_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('journey_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('touch_stage', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_id'], ['commercial_journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('touch_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touch_logs_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_touch_logs_merchant_id'), ['merchant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touch_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touch_logs_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_touch_logs_external_id'))

    op.drop_table('touch_logs')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('idx_orderitem_product')
        batch_op.drop_index('idx_orderitem_order')

    op.drop_table('order_items')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index('idx_variant_product')

    op.drop_table('product_variants')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_order_merchant_date')
        batch_op.drop_index('idx_order_customer')

    op.drop_table('orders')
    with op.batch_alter_table('floor_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floor_pricing_sku'))
        batch_op.drop_index(batch_op.f('ix_floor_pricing_shopify_product_id'))
        batch_op.drop_index('idx_floor_pricing_sku')
        batch_op.drop_index('idx_floor_pricing_merchant')

    op.drop_table('floor_pricing')
    op.drop_table('commercial_journeys')
    with op.batch_alter_table('async_auth_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_async_auth_status')
        batch_op.drop_index('idx_async_auth_merchant')
        batch_op.drop_index('idx_async_auth_inbox')

    op.drop_table('async_auth_requests')
    with op.batch_alter_table('action_reversals', schema=None) as batch_op:
        batch_op.drop_index('idx_reversal_merchant')

    op.drop_table('action_reversals')
    with op.batch_alter_table('token_vault', schema=None) as batch_op:
        batch_op.drop_index('idx_token_vault_status')
        batch_op.drop_index('idx_token_vault_merchant_provider')

    op.drop_table('token_vault')
    op.drop_table('store_dna')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_product_velocity')
        batch_op.drop_index('idx_product_merchant_dead')
        batch_op.drop_index('idx_product_last_sale')

    op.drop_table('products')
    with op.batch_alter_table('merchant_scope_grants', schema=None) as batch_op:
        batch_op.drop_index('idx_scope_grant_scope')
        batch_op.drop_index('idx_scope_grant_merchant_agent')

    op.drop_table('merchant_scope_grants')
    op.drop_table('merchant_journeys')
    op.drop_table('llm_usage_logs')
    op.drop_table('ledger_entries')
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_items_origin_execution_id'))
        batch_op.drop_index('idx_inbox_merchant_status')
        batch_op.drop_index('idx_inbox_created')

    op.drop_table('inbox_items')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('idx_customer_merchant_segment')
        batch_op.drop_index('idx_customer_last_order')

    op.drop_table('customers')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_origin_execution_id'))
        batch_op.drop_index('idx_campaign_merchant_status')

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_execution_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_thoughts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_thoughts_execution_id'))
        batch_op.drop_index('idx_thought_merchant_agent')
        batch_op.drop_index('idx_thought_created')

    op.drop_table('agent_thoughts')
    with op.batch_alter_table('agent_clients', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_client_merchant')
        batch_op.drop_index('idx_agent_client_client_id')

    op.drop_table('agent_clients')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index('idx_merchant_domain')

    op.drop_table('merchants')
    with op.batch_alter_table('governor_risk_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governor_risk_policies_agent_type'))

    op.drop_table('governor_risk_policies')
    op.drop_table('global_strategy_templates')
    with op.batch_alter_table('global_strategy_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_strategy_patterns_pattern_key'))

    op.drop_table('global_strategy_patterns')
    # ### end Alembic commands ###
